### PR TITLE
Move 'rebase' command to separate executable

### LINKED ISSUE #63: Move 'rebase' command to separate executable
This task is a part of #31

### PR DESCRIPTION
**Pull request by AntonKarabaza**
Closes #63

### CODE REVIEW

**Comment by extsoft** [comment]
@rultor please merge.

**Comment by extsoft** [comment]
@rultor stop

**Comment by extsoft** [comment]
@AntonKarabaza please fix the conflict.

**Comment by AntonKarabaza** [comment]
@extsoft Done.

**Comment by extsoft** [comment]
@rultor please merge

**Pull request merged**
