### PR TITLE
Move 'commands' command to separate executable

### LINKED ISSUE #80: Move 'commands' command to separate executable
This task is a part of #31

### PR DESCRIPTION
**Pull request by ivan-podorozhnyi**
Closes #80

### CODE REVIEW

**Comment by ivan-podorozhnyi** [comment]
@extsoft & @AntonKarabaza  I have no idea why, but renaming executable to git-elegant commands gives an error while running tests. Is it ok use executable without letter "S"?

**Comment by extsoft** [comment]
> Is it ok use executable without letter "S"?

@ivan-podorozhnyi No, it isn't. We need `commands`. Please try to find a root cause.

**Comment by ivan-podorozhnyi** [comment]
@extsoft Now it works fine. Thanks for helping to find the reason @AntonKarabaza

**Comment by extsoft** [comment]
@rultor please merge

**Pull request merged**
